-- Script de creación (el mismo que me compartiste)
-- Puedes ejecutarlo en SQL Developer: @database/script_creacion.sql
-- Incluye índices.

-- 1. TABLA USUARIO
CREATE TABLE USUARIO (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR2(100) NOT NULL,
    contrasenia VARCHAR2(128) NOT NULL,
    rol VARCHAR2(20) CHECK (rol IN ('ASISTENTE', 'GUARDA', 'CHOFER'))
);

-- 2. TABLA LOCALIDAD
CREATE TABLE LOCALIDAD (
    id_localidad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provincia VARCHAR2(100),
    canton VARCHAR2(100),
    distrito VARCHAR2(100),
    otras_senas VARCHAR2(200)
);

-- 3. TABLA RUTA
CREATE TABLE RUTA (
    id_ruta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chofer_asignado NUMBER,
    ruta_comunidad VARCHAR2(150),
    CONSTRAINT fk_ruta_chofer FOREIGN KEY (chofer_asignado)
        REFERENCES USUARIO (id_usuario)
        ON DELETE SET NULL
);

-- 4. TABLA ENCARGADO
CREATE TABLE ENCARGADO (
    id_encargado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_localidad NUMBER,
    nombre_encargado VARCHAR2(100) NOT NULL,
    apellido_encargado VARCHAR2(100) NOT NULL,
    telefono_encargado VARCHAR2(15),
    correo_encargado VARCHAR2(100),
    CONSTRAINT fk_encargado_localidad FOREIGN KEY (id_localidad)
        REFERENCES LOCALIDAD (id_localidad)
        ON DELETE SET NULL
);

-- 5. TABLA ESTUDIANTE
CREATE TABLE ESTUDIANTE (
    id_estudiante NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_localidad NUMBER,
    id_ruta NUMBER,
    id_encargado NUMBER,
    nombre VARCHAR2(100) NOT NULL,
    apellido_uno VARCHAR2(100) NOT NULL,
    apellido_dos VARCHAR2(100),
    telefono VARCHAR2(15),
    fotografia VARCHAR2(255),
    alerta_medica VARCHAR2(200),
    medicamento_prescrito VARCHAR2(200),
    CONSTRAINT fk_estudiante_localidad FOREIGN KEY (id_localidad)
        REFERENCES LOCALIDAD (id_localidad)
        ON DELETE SET NULL,
    CONSTRAINT fk_estudiante_ruta FOREIGN KEY (id_ruta)
        REFERENCES RUTA (id_ruta)
        ON DELETE SET NULL,
    CONSTRAINT fk_estudiante_encargado FOREIGN KEY (id_encargado)
        REFERENCES ENCARGADO (id_encargado)
        ON DELETE SET NULL
);

-- 6. TABLA PERMISO_SALIDA
CREATE TABLE PERMISO_SALIDA (
    id_permiso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante NUMBER NOT NULL,
    fecha_salida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    motivo VARCHAR2(200),
    autorizado_por VARCHAR2(100),
    CONSTRAINT fk_permiso_estudiante FOREIGN KEY (id_estudiante)
        REFERENCES ESTUDIANTE (id_estudiante)
        ON DELETE CASCADE
);

-- 7. TABLA CONSULTA
CREATE TABLE CONSULTA (
    id_consulta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_estudiante NUMBER NOT NULL,
    fecha_consulta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    accion VARCHAR2(20),
    CONSTRAINT fk_consulta_usuario FOREIGN KEY (id_usuario)
        REFERENCES USUARIO (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_consulta_estudiante FOREIGN KEY (id_estudiante)
        REFERENCES ESTUDIANTE (id_estudiante)
        ON DELETE CASCADE
);

-- Índices
CREATE INDEX idx_estudiante_nombre ON ESTUDIANTE(nombre, apellido_uno);
CREATE INDEX idx_permiso_fecha ON PERMISO_SALIDA(fecha_salida);
CREATE INDEX idx_encargado_nombre ON ENCARGADO(nombre_encargado);
