--------------------------------------------------------------------------------
-- Archivo: 10_tablas_usuarios_roles.sql
-- Proyecto: Expediente Digital Estudiantes de Secundaria
-- Curso: Bases de Datos
-- Motor: Oracle Database 19c
--
-- Objetivo:
-- Definir la estructura de seguridad lógica del sistema mediante:
--  - Roles
--  - Permisos
--  - Usuarios de la aplicación
--  - Relaciones N:M
--  - Protección de contraseñas mediante hash
--
-- NOTA:
-- La tabla usuario_app NO corresponde a los usuarios del motor Oracle (USERS),
-- sino a los usuarios de la aplicación.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1) TABLA ROL
--------------------------------------------------------------------------------
CREATE TABLE rol (
  id_rol       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre       VARCHAR2(50)  NOT NULL,
  descripcion  VARCHAR2(200),
  estado       CHAR(1) DEFAULT 'A' CHECK (estado IN ('A','I')),
  CONSTRAINT pk_rol PRIMARY KEY (id_rol),
  CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

--------------------------------------------------------------------------------
-- 2) TABLA PERMISO
--------------------------------------------------------------------------------
CREATE TABLE permiso (
  id_permiso   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  codigo       VARCHAR2(60)  NOT NULL, -- Ej: ESTUDIANTE_VER, EXPEDIENTE_EDITAR
  descripcion  VARCHAR2(200),
  CONSTRAINT pk_permiso PRIMARY KEY (id_permiso),
  CONSTRAINT uq_permiso_codigo UNIQUE (codigo)
);

--------------------------------------------------------------------------------
-- 3) TABLA ROL_PERMISO (Relación N:M)
--------------------------------------------------------------------------------
CREATE TABLE rol_permiso (
  id_rol       NUMBER NOT NULL,
  id_permiso   NUMBER NOT NULL,
  CONSTRAINT pk_rol_permiso PRIMARY KEY (id_rol, id_permiso),
  CONSTRAINT fk_rp_rol
    FOREIGN KEY (id_rol) REFERENCES rol(id_rol),
  CONSTRAINT fk_rp_permiso
    FOREIGN KEY (id_permiso) REFERENCES permiso(id_permiso)
);

--------------------------------------------------------------------------------
-- 4) TABLA USUARIO_APP (Usuarios de la aplicación)
--------------------------------------------------------------------------------
CREATE TABLE usuario_app (
  id_usuario     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  username       VARCHAR2(50)  NOT NULL,
  pass_hash      VARCHAR2(200) NOT NULL, -- Se almacena HASH, no texto plano
  nombre         VARCHAR2(100) NOT NULL,
  email          VARCHAR2(120),
  estado         CHAR(1) DEFAULT 'A' CHECK (estado IN ('A','I')),
  creado_en      DATE DEFAULT SYSDATE,
  creado_por     VARCHAR2(50),
  actualizado_en DATE,
  CONSTRAINT pk_usuario_app PRIMARY KEY (id_usuario),
  CONSTRAINT uq_usuario_username UNIQUE (username),
  CONSTRAINT uq_usuario_email    UNIQUE (email)
);

--------------------------------------------------------------------------------
-- 5) TABLA USUARIO_ROL (Relación N:M)
--------------------------------------------------------------------------------
CREATE TABLE usuario_rol (
  id_usuario NUMBER NOT NULL,
  id_rol     NUMBER NOT NULL,
  CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario, id_rol),
  CONSTRAINT fk_ur_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuario_app(id_usuario),
  CONSTRAINT fk_ur_rol
    FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);

--------------------------------------------------------------------------------
-- 6) FUNCIÓN PARA HASH DE CONTRASEÑAS
-- Utiliza SHA-256 mediante DBMS_CRYPTO
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_hash_password(p_password VARCHAR2)
RETURN RAW IS
BEGIN
  RETURN DBMS_CRYPTO.HASH(
    UTL_RAW.CAST_TO_RAW(p_password),
    DBMS_CRYPTO.HASH_SH256
  );
END;
/
--------------------------------------------------------------------------------
-- 7) TRIGGER PARA PROTEGER CONTRASEÑAS
-- Garantiza que NUNCA se almacenen en texto plano
--------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_usuario_app_hash
BEFORE INSERT OR UPDATE ON usuario_app
FOR EACH ROW
BEGIN
  IF INSERTING OR :NEW.pass_hash != :OLD.pass_hash THEN
    :NEW.pass_hash := fn_hash_password(:NEW.pass_hash);
    :NEW.actualizado_en := SYSDATE;
  END IF;
END;
/
--------------------------------------------------------------------------------
-- 8) ÍNDICES RECOMENDADOS
--------------------------------------------------------------------------------
CREATE INDEX ix_usuario_app_estado   ON usuario_app(estado);
CREATE INDEX ix_usuario_username     ON usuario_app(username);
CREATE INDEX ix_usuariorol_usuario   ON usuario_rol(id_usuario);
CREATE INDEX ix_rolpermiso_permiso   ON rol_permiso(id_permiso);

--------------------------------------------------------------------------------
-- 9) DATOS MÍNIMOS DE PRUEBA (OPCIONAL)
--------------------------------------------------------------------------------
INSERT INTO rol(nombre, descripcion)
VALUES ('ADMIN', 'Administrador del sistema');

INSERT INTO rol(nombre, descripcion)
VALUES ('DOCENTE', 'Docente del centro educativo');

INSERT INTO rol(nombre, descripcion)
VALUES ('ORIENTACION', 'Departamento de orientación');

INSERT INTO rol(nombre, descripcion)
VALUES ('CONSULTA', 'Usuario con acceso solo de lectura');

INSERT INTO permiso(codigo, descripcion)
VALUES ('EXPEDIENTE_VER', 'Consultar expediente del estudiante');

INSERT INTO permiso(codigo, descripcion)
VALUES ('EXPEDIENTE_EDITAR', 'Modificar datos del expediente');

INSERT INTO permiso(codigo, descripcion)
VALUES ('PERMISO_SALIDA_AUTORIZAR', 'Autorizar permisos de salida');

COMMIT;