
-- Archivo: /sql/10_tablas_usuarios_roles.sql
-- Ejecutar como: USUARIO DE PROYECTO (ej. EXPEDIENTE_DIGITAL)
-- Objetivo: Crear tablas base para el módulo de Usuarios/Roles/Permisos


-- 1) ROL
CREATE TABLE rol (
  id_rol       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre       VARCHAR2(50)  NOT NULL,
  descripcion  VARCHAR2(200),
  estado       CHAR(1) DEFAULT 'A' CHECK (estado IN ('A','I')),
  CONSTRAINT pk_rol PRIMARY KEY (id_rol),
  CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

-- 2) PERMISO 
CREATE TABLE permiso (
  id_permiso   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  codigo       VARCHAR2(60)  NOT NULL, -- ej: ESTUDIANTES_CREAR
  descripcion  VARCHAR2(200),
  CONSTRAINT pk_permiso PRIMARY KEY (id_permiso),
  CONSTRAINT uq_permiso_codigo UNIQUE (codigo)
);

-- 3) ROL_PERMISO (N:M)
CREATE TABLE rol_permiso (
  id_rol       NUMBER NOT NULL,
  id_permiso   NUMBER NOT NULL,
  CONSTRAINT pk_rol_permiso PRIMARY KEY (id_rol, id_permiso),
  CONSTRAINT fk_rp_rol     FOREIGN KEY (id_rol)    REFERENCES rol(id_rol),
  CONSTRAINT fk_rp_permiso FOREIGN KEY (id_permiso) REFERENCES permiso(id_permiso)
);

-- 4) USUARIO (de la aplicación: no confundir con USERS del sistema)
CREATE TABLE usuario_app (
  id_usuario   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  username     VARCHAR2(50)  NOT NULL,
  pass_hash    VARCHAR2(200) NOT NULL,  -- guarda hash, no texto plano
  nombre       VARCHAR2(100) NOT NULL,
  email        VARCHAR2(120),
  estado       CHAR(1) DEFAULT 'A' CHECK (estado IN ('A','I')),
  creado_en    DATE DEFAULT SYSDATE,
  CONSTRAINT pk_usuario_app PRIMARY KEY (id_usuario),
  CONSTRAINT uq_usuario_username UNIQUE (username),
  CONSTRAINT uq_usuario_email    UNIQUE (email)
);

-- 5) USUARIO_ROL (N:M)
CREATE TABLE usuario_rol (
  id_usuario NUMBER NOT NULL,
  id_rol     NUMBER NOT NULL,
  CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario, id_rol),
  CONSTRAINT fk_ur_usuario FOREIGN KEY (id_usuario) REFERENCES usuario_app(id_usuario),
  CONSTRAINT fk_ur_rol     FOREIGN KEY (id_rol)     REFERENCES rol(id_rol)
);

-- Índices recomendados para consultas
CREATE INDEX ix_usuario_app_estado  ON usuario_app(estado);
CREATE INDEX ix_usuario_username    ON usuario_app(username);
CREATE INDEX ix_usuariorol_usuario  ON usuario_rol(id_usuario);
CREATE INDEX ix_rolpermiso_permiso  ON rol_permiso(id_permiso);

-- Datos mínimos (opcionales) para probar
INSERT INTO rol(nombre, descripcion) VALUES ('ADMIN', 'Administrador del sistema');
INSERT INTO rol(nombre, descripcion) VALUES ('ASISTENTE', 'Asistente operativo');

INSERT INTO permiso(codigo, descripcion) VALUES ('USUARIOS_VER', 'Ver usuarios');
INSERT INTO permiso(codigo, descripcion) VALUES ('USUARIOS_CREAR', 'Crear usuarios');

COMMIT;