-- ============================================================================
-- Archivo : /database/usuarios_roles/50_triggers_usuarios_roles.sql
-- Ejecutar: @usuarios_roles/50_triggers_usuarios_roles.sql
-- Objetivo: 5 triggers del módulo Usuarios/Roles
-- Requisitos previos:
--   - Tablas del módulo (10_tablas_usuarios_roles.sql)
--   - Procedimientos y funciones (20_ y 30_)
-- ============================================================================

-- 0) Tablas de apoyo para auditoría (si no existen)
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE usuario_app_audit (
      id_audit     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      id_usuario   NUMBER,
      username     VARCHAR2(50),
      accion       VARCHAR2(10),   -- INSERT/UPDATE/DELETE
      detalle      VARCHAR2(4000),
      audit_at     DATE DEFAULT SYSDATE
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF; -- ignora "table already exists"
END;
/

-- 0.1) Asegurar columna de actualización si no existe
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_tab_cols
  WHERE table_name = 'USUARIO_APP'
    AND column_name = 'ACTUALIZADO_EN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuario_app ADD (actualizado_en DATE)';
  END IF;
END;
/

-- 1) TRG: Forzar email y username en minúsculas al insertar/actualizar
CREATE OR REPLACE TRIGGER trg_usuario_app_normaliza
BEFORE INSERT OR UPDATE ON usuario_app
FOR EACH ROW
BEGIN
  IF :NEW.username IS NOT NULL THEN
    :NEW.username := LOWER(:NEW.username);
  END IF;

  IF :NEW.email IS NOT NULL THEN
    :NEW.email := LOWER(:NEW.email);
  END IF;

  :NEW.actualizado_en := SYSDATE;
END;
/
SHOW ERRORS

-- 2) TRG: Auditoría de INSERT en usuario_app
CREATE OR REPLACE TRIGGER trg_usuario_app_audit_ins
AFTER INSERT ON usuario_app
FOR EACH ROW
BEGIN
  INSERT INTO usuario_app_audit (id_usuario, username, accion, detalle)
  VALUES (:NEW.id_usuario, :NEW.username, 'INSERT',
          'Creado usuario con estado='||:NEW.estado);
END;
/
SHOW ERRORS

-- 3) TRG: Auditoría de UPDATE en usuario_app
CREATE OR REPLACE TRIGGER trg_usuario_app_audit_upd
AFTER UPDATE ON usuario_app
FOR EACH ROW
DECLARE
  v_det VARCHAR2(4000);
BEGIN
  v_det := 'Cambio(s): ';

  IF NVL(:OLD.nombre,'?') <> NVL(:NEW.nombre,'?') THEN
    v_det := v_det || 'nombre: '||:OLD.nombre||' -> '||:NEW.nombre||'; ';
  END IF;

  IF NVL(:OLD.email,'?') <> NVL(:NEW.email,'?') THEN
    v_det := v_det || 'email: '||:OLD.email||' -> '||:NEW.email||'; ';
  END IF;

  IF NVL(:OLD.estado,'?') <> NVL(:NEW.estado,'?') THEN
    v_det := v_det || 'estado: '||:OLD.estado||' -> '||:NEW.estado||'; ';
  END IF;

  INSERT INTO usuario_app_audit (id_usuario, username, accion, detalle)
  VALUES (:NEW.id_usuario, :NEW.username, 'UPDATE', v_det);
END;
/
SHOW ERRORS

-- 4) TRG: Evitar eliminar ROL si está asignado a algún usuario
CREATE OR REPLACE TRIGGER trg_rol_no_delete_asignado
BEFORE DELETE ON rol
FOR EACH ROW
DECLARE
  v_usa NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_usa FROM usuario_rol WHERE id_rol = :OLD.id_rol;
  IF v_usa > 0 THEN
    RAISE_APPLICATION_ERROR(-20050, 'No se puede eliminar el rol: está asignado a usuarios.');
  END IF;
END;
/
SHOW ERRORS

-- 5) TRG: Asignar rol por defecto 'ASISTENTE' al crear usuario si no trae roles
--   Nota: requiere que exista el rol 'ASISTENTE'
CREATE OR REPLACE TRIGGER trg_usuario_rol_default
AFTER INSERT ON usuario_app
FOR EACH ROW
DECLARE
  v_id_rol rol.id_rol%TYPE;
  v_tiene  NUMBER;
BEGIN
  -- ¿Trae algún rol ya asignado vía app? (normalmente NO en este punto)
  SELECT COUNT(*) INTO v_tiene FROM usuario_rol WHERE id_usuario = :NEW.id_usuario;

  IF v_tiene = 0 THEN
    BEGIN
      SELECT id_rol INTO v_id_rol FROM rol WHERE UPPER(nombre) = 'ASISTENTE';
      INSERT INTO usuario_rol(id_usuario, id_rol) VALUES (:NEW.id_usuario, v_id_rol);
    EXCEPTION WHEN NO_DATA_FOUND THEN
      -- Si no existe el rol ASISTENTE, no hacemos nada (o podrías crearlo aquí)
      NULL;
    END;
  END IF;
END;
/
SHOW ERRORS

