--------------------------------------------------------------------------------
-- TABLA DE AUDITORÍA DEL SISTEMA
--------------------------------------------------------------------------------
CREATE TABLE AUDITORIA_SISTEMA (
    id_auditoria    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada  VARCHAR2(50)  NOT NULL,
    operacion       VARCHAR2(10)  NOT NULL,
    usuario_bd      VARCHAR2(50),
    fecha_evento    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    detalle         VARCHAR2(4000)
);